# Site settings
# Needs to be an absolute prefix
baseURL = "/"
title = "Casual Gaming "
theme = "fifty"
enableEmoji = true
DefaultContentLanguage = "no"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Casual Gaming"
  description = "Datatreff og spillkvelder i Trondheim"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []

  # Image used when shared on social media
  # Unset to disable
  # All 4 must be provided if enabled
  # Can be overridden in pages
  sharingImage = "/img/logo-large.png"
  sharingImageType = "image/png"
  sharingImageWidth = "1000"
  sharingImageHeight = "1000"

  # 404 error customization
  [params.error404]
    heading = "Siden finnes ikke"
    text = "Vennligst [gå hjem](/)."

  # Navigation Section
  [params.navigation]
    logo = "banner-logo.png"
    menu = "Meny"

    [[params.navigation.links]]
      name = "Hjem"
      url = "/"

    [[params.navigation.links]]
      name = "Om oss"
      url = "/om/"

    [[params.navigation.links]]
      name = "TrøndeLAN"
      #url = "/trondelan/"
      url = "https://trondelan.no"

    [[params.navigation.links]]
      name = "StudLAN"
      #url = "/studlan/"
      url = "https://studlan.no"

    [[params.navigation.links]]
      name = "For samarbeidspartnere"
      url = "/for-samarbeidspartnere/"

    [[params.navigation.links]]
      name = "Opptak"
      url = "/opptak/"

  # Banner section
  [params.banner]
    bannerImage = "/img/home/banner.jpg"
    logoImage = "/img/banner-logo.png"
    subtitle = "Datatreff og spillkvelder i Trondheim"

  # Tiles Section
  [params.tiles]
    enable = true

    [[params.tiles.showcase]]
      title = "TrøndeLAN"
      subtitle = "Trondheims største datatreff"
      image = "/img/home/trondelan.jpg"
      url = "https://trondelan.no"

    [[params.tiles.showcase]]
      title = "Discord"
      subtitle = "Join serveren vår!"
      image = "/img/home/studlan.jpg"
      url = "https://discord.casualgaming.no/"

    [[params.tiles.showcase]]
      title = "Om oss"
      subtitle = "Aktivitet, organisasjon, kontakt osv."
      image = "/img/home/konsoll_brett.jpg"
      url = "/om/"

    [[params.tiles.showcase]]
      title = "Opptak"
      subtitle = "Bli med på arrangeringen"
      image = "/img/home/opptak.jpg"
      url = "/opptak/"

  # About section
  [params.about]
    enable = true
    title = "Casual Gaming"
    subtitle = """
Casual Gaming (CaG) er en ideell student- og ungdomsorganisasjon som har til formål
å skape en felles sosial arena for spillinteresserte studenter og ungdom i Trondheimsområdet.
Vi arrangerer bl.a. **TrøndeLAN**, **StudLAN** og casual spillkvelder.

**[Les mer om oss her.](/om)**
"""

  # Partner section
  [params.partners]
    enable = true
    title = "Samarbeidspartnere"

    [[params.partners.partner]]
      image = "/img/partners/hyperion.png"
      alt = "Hyperion – Norsk Forbund for Fantastiske Fritidsinteresser"
      backgroundColor = ""
      url = "https://n4f.no/"
      description = "Vi er medlemsforening i Hyperion – Norsk Forbund for Fantastiske Fritidsinteresser"

    [[params.partners.partner]]
      image = "/img/partners/digitalkultur.png"
      alt = "Norsk Digital Kultur"
      backgroundColor = ""
      url = "https://www.digitalkultur.no/"
      description = "Vi er medlemsforening i Norsk Digital Kultur"

    [[params.partners.partner]]
      image = "/img/partners/online.png"
      alt = "Online, linjeforeningen for informatikk ved NTNU"
      backgroundColor = ""
      url = "https://online.ntnu.no/"
      description = "Vi har tilknytning til Online, linjeforeningen for informatikk ved NTNU"

    [[params.partners.partner]]
      #image = "/img/partners/TODO.png"
      alt = "Temporal AS"
      backgroundColor = ""
      url = "https://temporal.no/"
      description = "Temporal AS støtter oss med midler til å gjennomføre aktivitetene våre"

    [[params.partners.partner]]
      image = "/img/partners/vyos.svg"
      alt = "VyOS"
      backgroundColor = ""
      url = "https://vyos.io/"
      description = "VyOS støtter oss med et pro-abonnement for bruk av ruter-programvaren deres"

#    [[params.partners.partner]]
#      image = "/img/logo.png"
#      alt = "AAAaaa"
#      url = "https://example.net/"
#      description = "Støtter oss med en dedikert server for nettstedene våre"

#    [[params.partners.partner]]
#      image = ""
#      alt = "BBBbbb"
#      url = "https://example.net/"
#      description = "Støtter oss med en dedikert server for nettstedene våre"

  # Grasrotandelen section
  [params.grasrotandelen]
    enable = true
    url = "https://www.norsk-tipping.no/grasrotandelen/statistikk/iframe/993396605"

  # Discord section
  [params.discord]
    enable = true
    url = "https://discord.com/widget?id=153895015590920192&theme=dark"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Casual Gaming"

    [[params.footer.social]]
      icon = "fa-brands fa-facebook"
      url = "https://www.facebook.com/CasualGamingTrondheim/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-brands fa-discord"
      url = "https://discord.casualgaming.no/"
      label = "Discord"

    [[params.footer.social]]
      icon = "fa-brands fa-twitch"
      url = "https://www.twitch.tv/CasualGamingNorway"
      label = "Twitch 1"

    [[params.footer.social]]
      icon = "fa-brands fa-twitch"
      url = "https://www.twitch.tv/TrondeLAN"
      label = "Twitch 2"

    [[params.footer.social]]
      icon = "fa-brands fa-youtube"
      #url = "https://www.youtube.com/channel/UCwE4Udkp8A881Dfvbfa6KLQ"
      url = "https://www.youtube.com/user/studlanNTNU/"
      label = "YouTube"

    [[params.footer.social]]
      icon = "fa-brands fa-instagram"
      url = "https://www.instagram.com/casualgamingno"
      label = "Instagram"

    [[params.footer.social]]
      icon = "fa-brands fa-tiktok"
      url = "https://www.tiktok.com/@trondelan"
      label = "TikTok"

    # [[params.footer.social]]
    #   icon = "fa-brands fa-snapchat"
    #   url = "https://www.snapchat.com/add/casualgamingno"
    #   label = "Snapchat"

    [[params.footer.social]]
      icon = "fa-brands fa-github"
      url = "https://www.github.com/CasualGaming"
      label = "GitHub"

    # [[params.footer.social]]
    #   icon = "fa-solid fa-heartbeat"
    #   url = "https://status.casualgaming.no/"
    #   label = "Status"

    [[params.footer.social]]
      icon = "fa-solid fa-life-ring"
      url = "mailto:support@casualgaming.no"
      label = "Brukerstøtte"

    [[params.footer.social]]
      icon = "fa-solid fa-envelope"
      url = "mailto:post@casualgaming.no"
      label = "Kontakt"

    [[params.footer.line]]
      text = "Orgnr. [993 396 605](https://w2.brreg.no/enhet/sok/detalj.jsp?orgnr=993396605)"

    [[params.footer.line]]
      text = "[cag-web-2](https://github.com/CasualGaming/cag-web-2)"
