# Required secrets:
# - DOCKER_USERNAME
# - DOCKER_PASSWORD

name: CI/CD

env:
  DOCKER_IMAGE: casualgaming/cag-web-2

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  # release:
  #   types: [published]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: ${{ DOCKER_IMAGE }}:latest

  publish-bleeding:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ DOCKER_IMAGE }}:latest
